name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t soroush123/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true soroush123/react-test npm test
 
      - run: docker build -t soroush123/multi-client-10-14 ./client
      - run: docker build -t soroush123/multi-nginx-10-14 ./nginx
      - run: docker build -t soroush123/multi-server-10-14 ./server
      - run: docker build -t soroush123/multi-worker-10-14 ./worker
 
      - run: docker push soroush123/multi-client-10-14
      - run: docker push soroush123/multi-nginx-10-14
      - run: docker push soroush123/multi-server-10-14
      - run: docker push soroush123/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-980407370656
          region: us-east-1
          use_existing_version_if_available: true
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          
